name: Build Push and Create Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ACCOUNT_ID: 175948132408
  ECR_REPOSITORY: sw-redirect-micro-service
  LAMBDA_FUNCTION_NAME: sw-redirect-micro-service
  EXECUTION_ROLE_ARN: arn:aws:iam::175948132408:role/sw-redirect-lambda-execution-role
  ROLE_ARN: arn:aws:iam::175948132408:role/sw-redirect-github-actions
  MICRO_CMS_API_KEY: v78SMcjBh5dTz30DYLPCau4vIBk6VsanT0YI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login \
            --username AWS \
            --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY .

      - name: Tag image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag $ECR_REPOSITORY:latest \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Create Lambda if not exists
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          if aws lambda get-function --function-name $LAMBDA_FUNCTION_NAME 2>/dev/null; then
            echo "Lambda exists. Updating..."
            aws lambda update-function-code \
              --function-name $LAMBDA_FUNCTION_NAME \
              --image-uri $IMAGE_URI
          else
            echo "Creating Lambda..."
            aws lambda create-function \
              --function-name $LAMBDA_FUNCTION_NAME \
              --package-type Image \
              --code ImageUri=$IMAGE_URI \
              --role $EXECUTION_ROLE_ARN \
              --architectures x86_64 \
              --timeout 10 \
              --memory-size 128
          fi
      - name : Wait for Lambda update
        run: |
          aws lambda wait function-updated \
            --function-name $LAMBDA_FUNCTION_NAME
      - name: Update environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name $LAMBDA_FUNCTION_NAME \
            --environment "Variables={MICRO_CMS_API_KEY=$MICRO_CMS_API_KEY}"